services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=statspass
      - POSTGRES_USER=statsuser
      - POSTGRES_DB=statsdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "statsuser", "-d", "statsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  stats-server:
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspass
    networks:
      - ewm-network

  ewm-service:
    build: main-server
    image: main-server
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://explore-postgres-main:5432/explore-main
      - SPRING_DATASOURCE_USERNAME=explore-main
      - SPRING_DATASOURCE_PASSWORD=explore-main

  stats-db:
    image: postgres:16.1
    container_name: explore-postgres-stats-new
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_PASSWORD=explore-stats
      - POSTGRES_USER=explore-stats
      - POSTGRES_DB=explore-stats
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ewmuser", "-d", "ewmdb"]
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - ewm-network
  ewm-service:
    build:
      context: main-service
      dockerfile: Dockerfile
    image: ewm-service-image
    container_name: ewm-service
  main-db:
    image: postgres:16.1
    container_name: explore-postgres-main-new
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
      - "6545:5432"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmpass
      - STATS_SERVER_URL=http://stats-server:9090
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge