spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: "${spring.application.name}:${server.port}"
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/