server:
  port: 0
  uri: "http://localhost:${server.port}"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6544/explore-stats
    username: explore-stats
    password: explore-stats

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: always

main:
  banner-mode: off
  log-startup-info: false